export const languages = [
  { name: "Tiếng Anh" },
  { name: "Tiếng Trung" },
  { name: "Tiếng Tây Ban Nha" },
  { name: "Tiếng Hindi" },
  { name: "Tiếng Pháp" },
  { name: "Tiếng Ả Rập" },
  { name: "Tiếng Urdu" },
  { name: "Tiếng Nga" },
  { name: "Tiếng Bồ Đào Nha" },
  { name: "Tiếng Indo" },
  { name: "Tiếng Đức" },
  { name: "Tiếng Nhật" },
  { name: "Tiếng Việt" },
  { name: "Tiếng Hàn" },
];

export const genres = [
  { name: "Giả tưởng" },
  { name: "Kỳ bí" },
  { name: "Gây cấn" },
  { name: "Tình cảm" },
  { name: "Khoa học giả tưởng" },
  { name: "Thần thoại" },
  { name: "Lịch sử" },
  { name: "Kinh dị" },
  { name: "Phá án" },
  { name: "Phiêu lưu" },
  { name: "Thiếu niên" },
  { name: "Hiện thực" },
  { name: "Tiểu sử" },
  { name: "Hồi ký" },
  { name: "Self-help" },
  { name: "Kinh doanh/Tài chính" },
  { name: "Khoa học/Công nghệ" },
  { name: "Du lịch" },
  { name: "Thơ" },
  { name: "Truyện tranh" },
];
