export const languages = [
  { name: "Tiếng Anh" },
  { name: "Tiếng Trung" },
  { name: "Tiếng Tây Ban Nha" },
  { name: "Tiếng Hindi" },
  { name: "Tiếng Pháp" },
  { name: "Tiếng Ả Rập" },
  { name: "Tiếng Urdu" },
  { name: "Tiếng Nga" },
  { name: "Tiếng Bồ Đào Nha" },
  { name: "Tiếng Indo" },
  { name: "Tiếng Đức" },
  { name: "Tiếng Nhật" },
  { name: "Tiếng Việt" },
  { name: "Tiếng Hàn" },
];

export const genres = [
  { name: "Giả tưởng" },
  { name: "Kỳ bí" },
  { name: "Gây cấn" },
  { name: "Tình cảm" },
  { name: "Khoa học giả tưởng" },
  { name: "Thần thoại" },
  { name: "Lịch sử" },
  { name: "Kinh dị" },
  { name: "Phá án" },
  { name: "Phiêu lưu" },
  { name: "Thiếu niên" },
  { name: "Hiện thực" },
  { name: "Tiểu sử" },
  { name: "Hồi ký" },
  { name: "Self-help" },
  { name: "Kinh doanh/Tài chính" },
  { name: "Khoa học/Công nghệ" },
  { name: "Du lịch" },
  { name: "Thơ" },
  { name: "Truyện tranh" },
];

export const languageList = [
  "Tiếng Anh",
  "Tiếng Trung",
  "Tiếng Tây Ban Nha",
  "Tiếng Hindi",
  "Tiếng Pháp",
  "Tiếng Ả Rập",
  "Tiếng Urdu",
  "Tiếng Nga",
  "Tiếng Bồ Đào Nha",
  "Tiếng Indo",
  "Tiếng Đức",
  "Tiếng Nhật",
  "Tiếng Việt",
  "Tiếng Hàn",
]as const;

export const genreList = [
  "Giả tưởng",
  "Kỳ bí",
  "Gây cấn",
  "Tình cảm",
  "Khoa học giả tưởng",
  "Thần thoại",
  "Lịch sử",
  "Kinh dị",
  "Phá án",
  "Phiêu lưu",
  "Thiếu niên",
  "Hiện thực",
  "Tiểu sử",
  "Hồi ký",
  "Self-help",
  "Kinh doanh/Tài chính",
  "Khoa học/Công nghệ",
  "Du lịch",
  "Thơ",
  "Truyện tranh",
] as const;